:create_list:              /audience_lists.json
:remove_from_all_lists:    /audience_lists/remove_all
:destroy_list:             /audience_lists/%{list}
:add_to_list:              /audience_lists/%{list}/add
:remove_from_list:         /audience_lists/%{list}/remove
:audience_lists:           /audience_lists/lists.xml
:audience_list_members:    /audience_lists/%{list}/members.xml
:audience_members:         /audience_members
:get_audience_members:     /audience_members.xml
:search:                   /audience_members/search.xml
:memberships:              /audience_members/%{email}/lists.xml
:is_suppressed:            /audience_members/%{email}/is_suppressed
:update_user_email:        /audience_members/%{email}/update_email
:suppressed_since:         /audience_members/suppressed_since/%{timestamp}.txt
:suppress_user:            /suppressed_audience_members
:unsuppress_user:          /suppressed_audience_members/%{email}
:promotions:               /promotions.xml
:promotion_save:           /promotions/save
:mailing_stats:            /promotions/%{promotion_id}/mailings/%{mailing_id}.xml
:mailer:                   /mailer
:mailer_to_list:           /mailer/to_list
:mailer_to_all:            /mailer/to_all
:mailer_status:            /mailers/status/%{transaction_id}
:audience_list_size:       /audience_lists/%{list}/list_size
:audience_list_size_since: /audience_lists/%{list}/list_size_since/%{date}